import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from '@/app/context/Provider'
import './globals.css'
import Navbar from './components/layout/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white dark:bg-slate-800">
        <Providers>
          <Navbar />
            {children}
          </Providers> 
      </body>
    </html>
  )
}
